// app/api/cart/route.ts
import { NextResponse } from "next/server";

const cartItems = [
  {
    id: "p001",
    title: "無線滑鼠",
    description: "人體工學無線滑鼠，2.4GHz 傳輸",
    price: 499,
    count: 2,
    imgUrl: "https://via.placeholder.com/100x100?text=Mouse",
    subtotal: 998,
    inStock: true,
  },
  {
    id: "p002",
    title: "機械鍵盤",
    description: "青軸機械鍵盤，RGB 背光",
    price: 1299,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Keyboard",
    subtotal: 1299,
    inStock: true,
  },
  {
    id: "p003",
    title: "筆記型電腦支架",
    description: "鋁合金製造，可調高度",
    price: 699,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Laptop+Stand",
    subtotal: 699,
    inStock: true,
  },
  {
    id: "p004",
    title: "USB-C 集線器",
    description: "擴充 HDMI、USB 3.0、SD 卡槽",
    price: 899,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=USB+Hub",
    subtotal: 899,
    inStock: false,
  },
  {
    id: "p005",
    title: "27 吋顯示器",
    description: "4K UHD 顯示器，支援 HDR",
    price: 7999,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Monitor",
    subtotal: 7999,
    inStock: true,
  },
  {
    id: "p006",
    title: "藍牙耳機",
    description: "降噪真無線藍牙耳機，續航 24 小時",
    price: 1599,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Bluetooth+Earbuds",
    subtotal: 1599,
    inStock: true,
  },
  {
    id: "p007",
    title: "筆記本",
    description: "A5 精裝筆記本，80 張高質紙張",
    price: 199,
    count: 3,
    imgUrl: "https://via.placeholder.com/100x100?text=Notebook",
    subtotal: 597,
    inStock: true,
  },
  {
    id: "p008",
    title: "自動鉛筆",
    description: "0.5mm 精細書寫自動鉛筆",
    price: 59,
    count: 5,
    imgUrl: "https://via.placeholder.com/100x100?text=Pen",
    subtotal: 295,
    inStock: true,
  },
  {
    id: "p009",
    title: "行動電源",
    description: "20000mAh 快充行動電源",
    price: 899,
    count: 2,
    imgUrl: "https://via.placeholder.com/100x100?text=Powerbank",
    subtotal: 1798,
    inStock: false,
  },
  {
    id: "p010",
    title: "手寫板",
    description: "Wacom 初階繪圖板",
    price: 2499,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Tablet",
    subtotal: 2499,
    inStock: true,
  },
  {
    id: "p011",
    title: "滑鼠墊",
    description: "大面積防滑滑鼠墊",
    price: 299,
    count: 2,
    imgUrl: "https://via.placeholder.com/100x100?text=Mouse+Pad",
    subtotal: 598,
    inStock: true,
  },
  {
    id: "p012",
    title: "外接硬碟",
    description: "1TB USB 3.1 外接式硬碟",
    price: 2099,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=HDD",
    subtotal: 2099,
    inStock: true,
  },
  {
    id: "p013",
    title: "耳罩式耳機",
    description: "Studio 級高音質耳罩耳機",
    price: 1699,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Headphones",
    subtotal: 1699,
    inStock: true,
  },
  {
    id: "p014",
    title: "螢幕掛燈",
    description: "可調亮度，護眼螢幕燈條",
    price: 999,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Light+Bar",
    subtotal: 999,
    inStock: true,
  },
  {
    id: "p015",
    title: "手機架",
    description: "桌面用可折疊手機支架",
    price: 199,
    count: 2,
    imgUrl: "https://via.placeholder.com/100x100?text=Phone+Holder",
    subtotal: 398,
    inStock: true,
  },
  {
    id: "p016",
    title: "電腦背包",
    description: "防潑水多隔層筆電包",
    price: 1199,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Backpack",
    subtotal: 1199,
    inStock: true,
  },
  {
    id: "p017",
    title: "螢幕清潔組",
    description: "螢幕專用清潔液+布組合",
    price: 199,
    count: 2,
    imgUrl: "https://via.placeholder.com/100x100?text=Cleaner",
    subtotal: 398,
    inStock: true,
  },
  {
    id: "p018",
    title: "HDMI 線",
    description: "2 米高畫質 HDMI 傳輸線",
    price: 199,
    count: 3,
    imgUrl: "https://via.placeholder.com/100x100?text=HDMI",
    subtotal: 597,
    inStock: true,
  },
  {
    id: "p019",
    title: "延長線",
    description: "6 插座延長線，附USB孔",
    price: 499,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Power+Strip",
    subtotal: 499,
    inStock: false,
  },
  {
    id: "p020",
    title: "網路攝影機",
    description: "1080P 網路視訊攝影機",
    price: 899,
    count: 1,
    imgUrl: "https://via.placeholder.com/100x100?text=Webcam",
    subtotal: 899,
    inStock: true,
  },
];

// 取得 todos
export async function GET() {
  return NextResponse.json(cartItems);
}

// 新增 todo
export async function POST(req) {
  const body = await req.json();
  const newItem = {
    id: Date.now(),
    title: body.title,
    description: body.description,
    price: body,
    count: body.count,
    imgUrl: body,
    subtotal: body.count * body.price,
    inStock: true,
  };
  todos.push(newItem);
  return NextResponse.json(newItem, { status: 201 });
}
