import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

import Providers from "./providers";
import SideNav from "@/components/layout/sideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next + RTK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="bg-gray-50 ">
            <main className="m-auto w-7xl flex">
              <SideNav />
              <div className="bg-white p-2 grow min-h-dvh">{children}</div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
